### PR TITLE
add proxy->triggerByEventName($event) method

### PR DESCRIPTION
**Pull request by samsonasik**
another approach, keep trigger(PennyEventInterface), and add triggerByEventName($event) that allows string. /cc @gianarb

### CODE REVIEW

**Comment by samsonasik** [comment]
forwarded port #120 for cakephp eventmanager proxy, with additional `triggerByEventName($event)` feature

**Comment by gianarb** [comment]
At the moment I prefer replace current event_manager in penny.event_manager and it is a custom event manager that manage application flow.. :) And you can use another event manager to trigger your event into the application.. What do you think? :)

**Comment by samsonasik** [comment]
Ok ;)

Warm regards,

Abdul Malik Ikhsan

Pada 16 Nov 2015, pukul 22.19, Gianluca Arbezzano notifications@github.com menulis:

**Comment by gianarb** [comment]
At the moment I close this PR.. I am not interested to add this method..

Thanks!

**Pull request closed without merging**
