### PR TITLE
OC + PHPDoc

### PR DESCRIPTION
**Pull request by EmanueleMinotto**
- Object Calisthenics: based on https://github.com/object-calisthenics/phpcs-calisthenics-rules
- Code documentation

Missing `src/App.php` because requires more time to be studied, to be documented and to apply OC.

### CODE REVIEW

**Comment by EmanueleMinotto** [comment]
@gianarb please restart the Scrutinizer check, because this PR is ready
Thanks :)

**Comment by gianarb** [comment]
I don't undestand how restart it -.-..

Can you rebase i? :) maybe scrutinizer builds it another time :)

**Comment by EmanueleMinotto** [comment]
Done, let me know if everything is ok

**Comment by gianarb** [comment]
Perfect! Thanks

**Pull request merged**
