### PR TITLE
more improvements

### PR DESCRIPTION
**Pull request by samsonasik**
- PHPDiFactory refactor to allow set `useAnnotations` when call:

``` php
PHPDiFactory::buildContainer($config, true);
```

uses 2nd parameter to set it.
- EventManager documentation and its usage with PHPDiFactory
- Fixes missing use statements in getting started documentation.

### CODE REVIEW

**Comment by gianarb** [comment]
:+1:

**Comment by samsonasik** [comment]
woot, scrutinizer score now  9.76 \m/

**Comment by samsonasik** [comment]
https://scrutinizer-ci.com/g/pennyphp/penny/inspections/2a213cf5-c9f8-40e4-8710-6bff5431d187

**Comment by gianarb** [comment]
Thanks

**Pull request merged**
