### PR TITLE
add support trigger($eventName) and Cake\EventManager proxy

### PR DESCRIPTION
**Pull request by samsonasik**
@gianarb  this is to prove #118 and added `Cake\EventManager` proxy to prove ;)

### CODE REVIEW

**Comment by gianarb** [comment]
Thanks
Why have you drop the PennyEventManagerInterface? :) 

This interface define a compatible event

**Comment by samsonasik** [comment]
because it make hard to implement proxy for other Event Manager, it will get error like: `Cakephp\Event\EventManager dispatch must pass PennyEventManagerInterface, Cakephp\Event\Event passed`. We need to create a driver class that implements PennyEventManagerInterface just to make a proxy works, Also, provide a string event as key/event name is more usable imo.

**Comment by gianarb** [comment]
> We need to create a driver class that implements PennyEventManagerInterface just to make a proxy works

Yes without this step your events could not support `setRequest` or `setResponse` or `setRouteInfo`.. 
penny uses this methods https://github.com/pennyphp/penny/blob/master/src/App.php#L94
I understand that an unused interface is a bad practice.. But maybe this interface is helpful

Maybe we rename (I follow your old feedback) this `event_manager` in `penny.event_manager`.. :) The `penny.event_manager`manages only application flow.. :)

**Comment by samsonasik** [comment]
Ok, I understand, I will try to create separate PR for alternative that uses PennyEventInterface and proxy sample for cakephp.

Warm regards,

Abdul Malik Ikhsan

Pada 16 Nov 2015, pukul 15.32, Gianluca Arbezzano notifications@github.com menulis:

**Comment by gianarb** [comment]
Thanks :)

**Comment by samsonasik** [comment]
closing in favor of #120

**Comment by samsonasik** [comment]
@gianarb re-open, probably add another method: <code>setupEvent(PennyInterface $event)</code> for set event must be instance of `PennyEventInterface` ?

**Comment by samsonasik** [comment]
re-closing, seems not possible :p

**Comment by samsonasik** [comment]
Hm...., how about add triggerByEventName() ?

Warm regards,

Abdul Malik Ikhsan

Pada 16 Nov 2015, pukul 15.56, Gianluca Arbezzano notifications@github.com menulis:

**Pull request closed without merging**
