### PR TITLE
remove unused $request and $response property

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by gianarb** [comment]
Thanks

**Comment by samsonasik** [comment]
why close ? not merge ?

**Comment by gianarb** [comment]
Because I'm crazy!!! :dancer:

**Comment by gianarb** [comment]
Sorry :+1:

**Comment by samsonasik** [comment]
any reason to not remove the $request and $response property?

**Comment by samsonasik** [comment]
ok (y)

**Pull request merged**
