### PR TITLE
add more tests

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
I will try add more tests when I'm back in next few hours.

**Comment by gianarb** [comment]
Thanks! :) I wait your feedback before merge this pr :)

**Comment by samsonasik** [comment]
I am back, I will try to add more tests now

**Comment by samsonasik** [comment]
Current coverage:

penny-cov

I still don't know how to tests this line : https://github.com/pennyphp/penny/blob/master/src/App.php#L106-L108 

Enough for now I think ;)

**Comment by gianarb** [comment]
np.. To test this line is needed a wrong dispatcher.. :) 

Thanks!

**Comment by samsonasik** [comment]
now 100% tested \m/

**Comment by samsonasik** [comment]
penny-cov-100

**Comment by gianarb** [comment]
Thanks!

**Pull request merged**
