### PR TITLE
php 7 requirement definition

### PR DESCRIPTION
**Pull request by samsonasik**
see https://twitter.com/Ocramius/status/658225000546238464 because ocramius is always right ;)

### CODE REVIEW

**Comment by gianarb** [comment]
@Ocramius we are ready!

**Comment by Ocramius** [comment]
:+1:

**Comment by samsonasik** [comment]
@gianarb then it ready for merge ;)

**Comment by gianarb** [comment]
Merged #100

**Comment by gianarb** [comment]
Thanks!

**Pull request merged**
