### PR TITLE
remove ->getContainer() call inside internal App class inside setUpEventWithRequestResponse() method

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by gianarb** [comment]
I am not interested to remove this method.. 
Why would you remove it?

**Comment by samsonasik** [comment]
it is called in internal method, like on `getEventManager()`, we just use `$this->container->get('event_manager');`, if we call outside, we still can call `$app->getContainer()`

**Comment by samsonasik** [comment]
I don't remove the `getContainer()` method, I just remove its call, `->getContainer()` inside App class, if we need call outside, we still can call `$app->getContainer()`

**Comment by samsonasik** [comment]
@gianarb I think the better PR title is "remove ->getContainer() call inside internal App class **inside setUpEventWithRequestResponse()** method" I will update PR title

**Comment by gianarb** [comment]
At the moment I don't see ways to remove this method.. Maybe we can remove it in the future ;)

**Comment by samsonasik** [comment]
why? this is called in inside `setUpEventWithRequestResponse()`, if we need call after instantiation, we still can call `$app->getContainer()`, but not inside App class, also, for consistency in compare with container call inside `getEventManager()` method.

**Comment by samsonasik** [comment]
again, I'm not remove `getContainer()` method, I just removed its call inside App class method, and for consistency with getEventManager() which is used `$this->container` instead.

**Comment by gianarb** [comment]
Thanks

**Pull request merged**
